version: '3'

services:
  # service1 lesson6 docker-compose веб-сервер HTTPD 2.4
  webserver:
    image: docker.io/library/httpd:latest
    ports:
      - "86:80"
    volumes:
      - ./web-content:/usr/local/apache2/htdocs
    networks:
      - docker-compose
    configs:
      - httpd_config

  # service2 lesson6 docker-compose СУБД-сервер PostgreSQL 16.2
  postgres:
    image: docker.io/postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: docker-compose
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - docker-compose

networks:
  docker-compose:
    driver: bridge

configs:
  httpd_config:
    file: ./httpd1.conf
    file: ./admin.conf
volumes:
  postgres-data:
